language: cpp

compiler:
 - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-cache search microhttpd
 - sudo apt-get install -qq gcov protobuf-compiler libprotobuf-lite7 libprotobuf-dev libprotoc-dev bison flex libftdi-dev libftdi1 libusb-1.0-0-dev liblo-dev libavahi-client-dev uuid-dev libcppunit-dev libcppunit-1.12-1 libncurses5-dev python-protobuf libmicrohttpd-dev
 - sudo pip install cpp-coveralls

script:
 - autoreconf -i && ./configure --enable-gcov && make && make check

after_success:
 - coveralls --verbose --exclude lib --exclude tests --gcov-options '\-lp'

cache: apt
