language: cpp

script:
  - "bash -ex .travis-ci.sh"

matrix:
  fast_finish: true
  include:
    - compiler: clang
      env: TASK='compile'
    - compiler: gcc
      env: TASK='compile'
    - env: TASK='doxygen'
    - env: TASK='lint'
    - env: TASK='check-licences'

cache: apt

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-cache search microhttpd
 - sudo apt-get install -qq protobuf-compiler libprotobuf-lite7 libprotobuf-dev libprotoc-dev bison flex libftdi-dev libftdi1 libusb-1.0-0-dev liblo-dev libavahi-client-dev uuid-dev libcppunit-dev libcppunit-1.12-1 libncurses5-dev python-protobuf libmicrohttpd-dev
#g++-4.9 won't work on Ubuntu 12.04 that Travis currently uses
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
#Remove the old g++/gcc to ensure we're using the latest ones
 - if [ "$CXX" = "g++" ]; then sudo rm /usr/bin/g++; sudo rm /usr/bin/gcc; fi
#Install doxygen if required
 - if [ "$TASK" = "doxygen" ]; then sudo apt-get install -qq doxygen; fi

notifications:
  irc:
    channels:
     - "chat.freenode.net#openlighting"
    on_success: change
    on_failure: change

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "fa0kF0GSMCeX6HL2xBjUkqqSh2xECVcTpGYREK1Syts8cKyUkmKY5hLdlChFq1Qq2PGPHlsGSMI4X4OtqaojjkBrrtP3vKnsBnOQ1R53VYiK168IDNMiXsEJF3Uxf/JUuLaZ9H4wm4RSLKf9VlT3YSA+ZHuWcHq4zejIJxEVENI="

addons:
  coverity_scan:
    project:
      name: "OpenLightingProject/ola"
      description: "Build submitted via Travis CI"
    notification_email: ola-coverity@openlighting.org
    build_command:   "bash -ex .travis-ci.sh"
    branch_pattern: master
