language: cpp
compiler:
  - gcc
  - clang
script: autoreconf -i && ./configure && make

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq protobuf-compiler libprotobuf-lite7 libprotobuf-dev libprotoc-dev bison flex libftdi-dev  libftdi1 libusb-1.0-0-dev liblo-dev libavahi-client-dev uuid-dev
