language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "NCr/adkHKiiz8UY7C/4fOGuphC1ePJVXHjR6vP0D5gUs0TTaG570Zn4dFl+SV6h1fEkK3h48hF5UgYsqD9WVFkrAVbg26aKM7iwsEjPGTXNplC4mFZH7A5vORGLypixNhmW9i160UOqXjFVexUpyMaMQxlHU8snOpq3mLLmZ95k="

script:
 - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then bash -ex .travis-ci.sh; fi

cache: apt

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq protobuf-compiler libprotobuf-lite7 libprotobuf-dev libprotoc-dev bison flex libftdi-dev libftdi1 libusb-1.0-0-dev liblo-dev libavahi-client-dev uuid-dev libcppunit-dev libcppunit-1.12-1 libncurses5-dev python-protobuf libmicrohttpd-dev
#g++-4.9 won't work on Ubuntu 12.04 that Travis currently uses
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
#Remove the old g++/gcc to ensure we're using the latest ones
 - if [ "$CXX" = "g++-4.8" ]; then sudo rm /usr/bin/g++; sudo rm /usr/bin/gcc; fi
#Install coveralls if required
 - if [ "$TASK" = "coverage" ]; then sudo pip install -qq cpp-coveralls; fi
#Install doxygen if required
 - if [ "$TASK" = "doxygen" ]; then sudo apt-get install -qq doxygen; fi

after_success:
  - if [ "$TASK" = "coverage" ]; then coveralls --gcov /usr/bin/gcov-4.8 -b . -E '.*Test\.cpp$' --gcov-options '\-lp' > /dev/null; fi

notifications:
  irc:
    channels:
     - "chat.freenode.net#openlighting"
    on_success: change
    on_failure: change

addons:
  coverity_scan:
    project:
      name: "peternewman/ola"
      description: "OLA Coverity test"
    notification_email: ola-coverity@pjnewman.co.uk
    build_command_prepend: "autoreconf -i && ./configure"
    build_command:   "make"
    branch_pattern: coverity_scan
